"""empty message

Revision ID: a2dd174add0c
Revises: da3e86948e02
Create Date: 2021-02-13 01:27:31.554782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dd174add0c'
down_revision = 'da3e86948e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WebsiteContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('sub_headline', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('nutshell', sa.String(), nullable=True),
    sa.Column('blurb', sa.String(), nullable=True),
    sa.Column('pullout', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_description', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WebsiteContent')
    # ### end Alembic commands ###
