"""empty message

Revision ID: aa8e2fc15974
Revises: 
Create Date: 2021-02-08 05:08:19.703152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8e2fc15974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('writtenBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('writtenBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Content')
    op.drop_table('Column')
    # ### end Alembic commands ###
