"""empty message

Revision ID: b89818d00982
Revises: 0797c93baed6
Create Date: 2021-02-13 06:00:17.851599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89818d00982'
down_revision = '0797c93baed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('date_from_date', sa.String(), nullable=True),
    sa.Column('date_from_time', sa.String(), nullable=True),
    sa.Column('date_to_date', sa.String(), nullable=True),
    sa.Column('date_to_time', sa.String(), nullable=True),
    sa.Column('contactFirstName', sa.String(), nullable=True),
    sa.Column('contactLastName', sa.String(), nullable=True),
    sa.Column('contactOfficeTel', sa.String(), nullable=True),
    sa.Column('contactMobileNum', sa.String(), nullable=True),
    sa.Column('contactEmail', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    # ### end Alembic commands ###
