"""empty message

Revision ID: da3e86948e02
Revises: 805c612a4735
Create Date: 2021-02-13 00:49:15.400702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3e86948e02'
down_revision = '805c612a4735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddtionalContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('writtenBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('cellPhone', sa.String(), nullable=True),
    sa.Column('workPhone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EdtionBudget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_page', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('total_advertisement', sa.String(), nullable=True),
    sa.Column('no_of_color_pages', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('date_from_date', sa.String(), nullable=True),
    sa.Column('date_from_time', sa.String(), nullable=True),
    sa.Column('date_to_date', sa.String(), nullable=True),
    sa.Column('date_to_time', sa.String(), nullable=True),
    sa.Column('contactFirstName', sa.String(), nullable=True),
    sa.Column('contactLastName', sa.String(), nullable=True),
    sa.Column('contactOfficeTel', sa.String(), nullable=True),
    sa.Column('contactMobileNum', sa.String(), nullable=True),
    sa.Column('contactEmail', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OpEd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('writtenBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postID', sa.String(), nullable=True),
    sa.Column('postType', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('photoCaption', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('filePath', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('captionUpdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postID', sa.String(), nullable=True),
    sa.Column('postType', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('photoCaption', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('filePath', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('captionUpdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SocialMediaExcerpt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('writtenBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SocialMediaSchedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('review', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ThisWeekMinute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('draftID', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('myTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskTitle', sa.String(), nullable=True),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('dueDate', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('assignedTo', sa.Integer(), nullable=True),
    sa.Column('assigneeID', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myTask')
    op.drop_table('ThisWeekMinute')
    op.drop_table('SocialMediaSchedule')
    op.drop_table('SocialMediaExcerpt')
    op.drop_table('Resource')
    op.drop_table('Photo')
    op.drop_table('OpEd')
    op.drop_table('Events')
    op.drop_table('EdtionBudget')
    op.drop_table('Contact')
    op.drop_table('AddtionalContent')
    # ### end Alembic commands ###
